name: Deploy Terraform and Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      TF_VAR_region: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2 # Use v2 for better security
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }} # Use env variable

      - name: Initialize Terraform
        working-directory: terraform/
        run: terraform init

      - name: Plan Terraform
        working-directory: terraform/
        run: terraform plan -out=tfplan -var "key_name=ansible"

      - name: Apply Terraform
        working-directory: terraform/
        run: terraform apply -auto-approve tfplan

      - name: Get Public IP
        id: get_public_ip
        working-directory: terraform/
        run: |
          echo "PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
          echo "::set-output name=ip::$PUBLIC_IP"  # Keep this line for backwards compatibility (optional)

      - name: Save SSH Key and Update Inventory
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PEM_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan ${{ steps.get_public_ip.outputs.ip }} >> ~/.ssh/known_hosts # Add EC2 host key
          echo "[all]" > ansible/inventory.ini # Use ini format for simplicity
          echo "${{ steps.get_public_ip.outputs.ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory.ini

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml -vvv # Reduced verbosity unless needed
